import { Product } from "./data";

export const extendedProducts: Product[] = [
    {
        "id": 100,
        "category": "General",
        "name": "1 Pcs Dust Proof Coat Cover",
        "price": "3186",
        "originalPrice": "9314",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/1 Pcs Dust Proof Coat Cover/CoatCover.jpg",
        "description": "High-quality 1 Pcs Dust Proof Coat Cover for your everyday needs."
    },
    {
        "id": 101,
        "category": "General",
        "name": "1 Pcs Stainless Steel Soap Holder - B15",
        "price": "2776",
        "originalPrice": "10529",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/1 Pcs Stainless Steel Soap Holder - B15/SoapHolder.jpg",
        "description": "High-quality 1 Pcs Stainless Steel Soap Holder - B15 for your everyday needs."
    },
    {
        "id": 102,
        "category": "General",
        "name": "10 Pcs Plastic Serving Plates",
        "price": "2563",
        "originalPrice": "8858",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/10 Pcs Plastic Serving Plates/IMG-20250817-WA0020.jpg",
        "description": "High-quality 10 Pcs Plastic Serving Plates for your everyday needs."
    },
    {
        "id": 103,
        "category": "General",
        "name": "10 Pcs Tool Kit",
        "price": "2753",
        "originalPrice": "10770",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/10 Pcs Tool Kit/IMG-20250821-WA0195.jpg",
        "description": "High-quality 10 Pcs Tool Kit for your everyday needs."
    },
    {
        "id": 104,
        "category": "General",
        "name": "115 Pcs Tool Kit",
        "price": "1959",
        "originalPrice": "10314",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/115 Pcs Tool Kit/115ToolKit.jpg",
        "description": "High-quality 115 Pcs Tool Kit for your everyday needs."
    },
    {
        "id": 105,
        "category": "General",
        "name": "13 Piece Makeup Brush",
        "price": "3304",
        "originalPrice": "10740",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/13 Piece Makeup Brush/IMG-20250821-WA0180.jpg",
        "description": "High-quality 13 Piece Makeup Brush for your everyday needs."
    },
    {
        "id": 106,
        "category": "General",
        "name": "15 Inch Lightweight Laptop Bag",
        "price": "2578",
        "originalPrice": "9490",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/15 Inch Lightweight Laptop Bag/IMG-20250821-WA0176.jpg",
        "description": "High-quality 15 Inch Lightweight Laptop Bag for your everyday needs."
    },
    {
        "id": 107,
        "category": "General",
        "name": "2 In 1 Eyebrow And Facial Trimmer",
        "price": "803",
        "originalPrice": "10376",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/2 In 1 Eyebrow And Facial Trimmer/IMG-20250821-WA0192.jpg",
        "description": "High-quality 2 In 1 Eyebrow And Facial Trimmer for your everyday needs."
    },
    {
        "id": 108,
        "category": "General",
        "name": "2 IN 1 Smart Wifi Camera",
        "price": "3727",
        "originalPrice": "6219",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/2 IN 1 Smart Wifi Camera/wifiCamera.jpg",
        "description": "High-quality 2 IN 1 Smart Wifi Camera for your everyday needs."
    },
    {
        "id": 109,
        "category": "General",
        "name": "2 Layer Steel Soap Rack",
        "price": "3846",
        "originalPrice": "9604",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/2 Layer Steel Soap Rack/soapRack.jpg",
        "description": "High-quality 2 Layer Steel Soap Rack for your everyday needs."
    },
    {
        "id": 110,
        "category": "General",
        "name": "3 Layer Cloth Rack",
        "price": "1656",
        "originalPrice": "6290",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/3 Layer Cloth Rack/clothRack.jpg",
        "description": "High-quality 3 Layer Cloth Rack for your everyday needs."
    },
    {
        "id": 111,
        "category": "General",
        "name": "3 Pcs Stainless Steel Airtight Container",
        "price": "1063",
        "originalPrice": "6333",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/3 Pcs Stainless Steel Airtight Container/AirtightContainer.jpg",
        "description": "High-quality 3 Pcs Stainless Steel Airtight Container for your everyday needs."
    },
    {
        "id": 112,
        "category": "General",
        "name": "360 rotatable & stable cosmetic organizer",
        "price": "2328",
        "originalPrice": "10342",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/360 rotatable & stable cosmetic organizer/rotatable.jpg",
        "description": "High-quality 360 rotatable & stable cosmetic organizer for your everyday needs."
    },
    {
        "id": 113,
        "category": "General",
        "name": "3M Nano Tape",
        "price": "1713",
        "originalPrice": "8833",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/3M Nano Tape/IMG-20250821-WA0062.jpg",
        "description": "High-quality 3M Nano Tape for your everyday needs."
    },
    {
        "id": 114,
        "category": "General",
        "name": "4 In 1 Korean Style Backpack",
        "price": "4365",
        "originalPrice": "7975",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/4 In 1 Korean Style Backpack/koreanStyle.jpg",
        "description": "High-quality 4 In 1 Korean Style Backpack for your everyday needs."
    },
    {
        "id": 115,
        "category": "General",
        "name": "4 Tier Corner Shelf",
        "price": "808",
        "originalPrice": "10926",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/4 Tier Corner Shelf/cornerShelf.jpg",
        "description": "High-quality 4 Tier Corner Shelf for your everyday needs."
    },
    {
        "id": 116,
        "category": "General",
        "name": "4 Tier Movable Rack",
        "price": "1299",
        "originalPrice": "6228",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/4 Tier Movable Rack/Movable Rack.jpg",
        "description": "High-quality 4 Tier Movable Rack for your everyday needs."
    },
    {
        "id": 117,
        "category": "General",
        "name": "40 Pcs Combination Socket Wrench Set",
        "price": "3647",
        "originalPrice": "9345",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/40 Pcs Combination Socket Wrench Set/WhatsApp Image 2025-08-18 at 14.34.19_8026ea6f.jpg",
        "description": "High-quality 40 Pcs Combination Socket Wrench Set for your everyday needs."
    },
    {
        "id": 118,
        "category": "General",
        "name": "5 In 1 Hot Hair Styler",
        "price": "1262",
        "originalPrice": "9348",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/5 In 1 Hot Hair Styler/HotHair Styler.jpg",
        "description": "High-quality 5 In 1 Hot Hair Styler for your everyday needs."
    },
    {
        "id": 119,
        "category": "General",
        "name": "6 Pcs Round Strainer",
        "price": "2693",
        "originalPrice": "10870",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/6 Pcs Round Strainer/RoundStrainer.jpg",
        "description": "High-quality 6 Pcs Round Strainer for your everyday needs."
    },
    {
        "id": 120,
        "category": "General",
        "name": "85cm Sink Dish Drying Rack",
        "price": "5102",
        "originalPrice": "7646",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/85cm Sink Dish Drying Rack/DryingRack.jpg",
        "description": "High-quality 85cm Sink Dish Drying Rack for your everyday needs."
    },
    {
        "id": 121,
        "category": "General",
        "name": "A9 Mini Wireless Camera",
        "price": "5312",
        "originalPrice": "10199",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/A9 Mini Wireless Camera/A9MINI.jpg",
        "description": "High-quality A9 Mini Wireless Camera for your everyday needs."
    },
    {
        "id": 122,
        "category": "General",
        "name": "Adjustable Hot shaper Belt",
        "price": "4841",
        "originalPrice": "10413",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Adjustable Hot shaper Belt/Belt.jpg",
        "description": "High-quality Adjustable Hot shaper Belt for your everyday needs."
    },
    {
        "id": 123,
        "category": "General",
        "name": "Air Fryer Leaf paper (100pcs)",
        "price": "2542",
        "originalPrice": "10856",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Air Fryer Leaf paper (100pcs)/IMG-20250822-WA0069.jpg",
        "description": "High-quality Air Fryer Leaf paper (100pcs) for your everyday needs."
    },
    {
        "id": 124,
        "category": "General",
        "name": "air prod",
        "price": "2874",
        "originalPrice": "8399",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/air prod/airpod.jpg",
        "description": "High-quality air prod for your everyday needs."
    },
    {
        "id": 125,
        "category": "General",
        "name": "Aluminium Waterproof Foil Stickers (60cm2m)",
        "price": "1887",
        "originalPrice": "10610",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Aluminium Waterproof Foil Stickers (60cm2m)/Aluminium.jpg",
        "description": "High-quality Aluminium Waterproof Foil Stickers (60cm2m) for your everyday needs."
    },
    {
        "id": 126,
        "category": "General",
        "name": "Animal Design Digital Thermometer",
        "price": "1114",
        "originalPrice": "9167",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Animal Design Digital Thermometer/thermometer.jpg",
        "description": "High-quality Animal Design Digital Thermometer for your everyday needs."
    },
    {
        "id": 127,
        "category": "General",
        "name": "Animal Slap Bracelet - Stitch Doll",
        "price": "5456",
        "originalPrice": "10663",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Animal Slap Bracelet - Stitch Doll/AnimalSlapBracelet.jpg",
        "description": "High-quality Animal Slap Bracelet - Stitch Doll for your everyday needs."
    },
    {
        "id": 128,
        "category": "General",
        "name": "Anti Theft Multi Functional Usb Back Pack",
        "price": "718",
        "originalPrice": "10438",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Anti Theft Multi Functional Usb Back Pack/Backpack.jpg",
        "description": "High-quality Anti Theft Multi Functional Usb Back Pack for your everyday needs."
    },
    {
        "id": 129,
        "category": "General",
        "name": "Automatic Toothpaste Dispenser",
        "price": "3734",
        "originalPrice": "9213",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Automatic Toothpaste Dispenser/IMG-20250821-WA0120.jpg",
        "description": "High-quality Automatic Toothpaste Dispenser for your everyday needs."
    },
    {
        "id": 130,
        "category": "General",
        "name": "Baby Round Frame Sunglasses",
        "price": "1295",
        "originalPrice": "10887",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Baby Round Frame Sunglasses/saunglasses.jpg",
        "description": "High-quality Baby Round Frame Sunglasses for your everyday needs."
    },
    {
        "id": 131,
        "category": "General",
        "name": "Bath Foot Massager Pad",
        "price": "4588",
        "originalPrice": "7708",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Bath Foot Massager Pad/WhatsApp Image 2025-08-18 at 15.11.28_7ce47089.jpg",
        "description": "High-quality Bath Foot Massager Pad for your everyday needs."
    },
    {
        "id": 132,
        "category": "General",
        "name": "Bedroom Multifunctional Corner Cloth & Coat Rack",
        "price": "3439",
        "originalPrice": "6138",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Bedroom Multifunctional Corner Cloth & Coat Rack/WhatsApp Image 2025-08-28 at 18.02.45_489f4221.jpg",
        "description": "High-quality Bedroom Multifunctional Corner Cloth & Coat Rack for your everyday needs."
    },
    {
        "id": 133,
        "category": "General",
        "name": "Blackboard Wall Sticker With Chalk 60x200cm",
        "price": "1360",
        "originalPrice": "10678",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Blackboard Wall Sticker With Chalk 60x200cm/WallSticker.jpg",
        "description": "High-quality Blackboard Wall Sticker With Chalk 60x200cm for your everyday needs."
    },
    {
        "id": 134,
        "category": "General",
        "name": "Bottle Umbrella",
        "price": "948",
        "originalPrice": "8940",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Bottle Umbrella/BottleUmbrella.jpg",
        "description": "High-quality Bottle Umbrella for your everyday needs."
    },
    {
        "id": 135,
        "category": "General",
        "name": "Box Shape Elegant Cutting Board",
        "price": "4064",
        "originalPrice": "8572",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Box Shape Elegant Cutting Board/cuttingBoard.jpg",
        "description": "High-quality Box Shape Elegant Cutting Board for your everyday needs."
    },
    {
        "id": 136,
        "category": "General",
        "name": "C Shaped Side Table",
        "price": "3299",
        "originalPrice": "7851",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/C Shaped Side Table/C shaped table.jpg",
        "description": "High-quality C Shaped Side Table for your everyday needs."
    },
    {
        "id": 137,
        "category": "General",
        "name": "cable",
        "price": "3881",
        "originalPrice": "6849",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/cable/cable.jpg",
        "description": "High-quality cable for your everyday needs."
    },
    {
        "id": 138,
        "category": "General",
        "name": "Dancing Cactus",
        "price": "5321",
        "originalPrice": "8391",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Dancing Cactus/DancingCactus.jpg",
        "description": "High-quality Dancing Cactus for your everyday needs."
    },
    {
        "id": 139,
        "category": "General",
        "name": "derma roller",
        "price": "5004",
        "originalPrice": "9702",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/derma roller/IMG-20250823-WA0021.jpg",
        "description": "High-quality derma roller for your everyday needs."
    },
    {
        "id": 140,
        "category": "General",
        "name": "Derma Roller - DRS",
        "price": "1717",
        "originalPrice": "6337",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Derma Roller - DRS/DermaRoller.jpg",
        "description": "High-quality Derma Roller - DRS for your everyday needs."
    },
    {
        "id": 141,
        "category": "General",
        "name": "Drop ship Price",
        "price": "697",
        "originalPrice": "7600",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Drop ship Price/WhatsApp Image 2025-08-20 at 20.07.42_20855c78.jpg",
        "description": "High-quality Drop ship Price for your everyday needs."
    },
    {
        "id": 142,
        "category": "General",
        "name": "Earth Star Fry Pan - 20cm",
        "price": "1202",
        "originalPrice": "9327",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Earth Star Fry Pan - 20cm/pan.jpg",
        "description": "High-quality Earth Star Fry Pan - 20cm for your everyday needs."
    },
    {
        "id": 143,
        "category": "General",
        "name": "Eva Yoga Mat - 4cm",
        "price": "3074",
        "originalPrice": "7460",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Eva Yoga Mat - 4cm/IMG-20250821-WA0188.jpg",
        "description": "High-quality Eva Yoga Mat - 4cm for your everyday needs."
    },
    {
        "id": 144,
        "category": "General",
        "name": "Fast Heating electric knee pad",
        "price": "5334",
        "originalPrice": "8797",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Fast Heating electric knee pad/fastheating.jpg",
        "description": "High-quality Fast Heating electric knee pad for your everyday needs."
    },
    {
        "id": 145,
        "category": "General",
        "name": "Flawless Rechargable Facial Trimmer",
        "price": "5041",
        "originalPrice": "7634",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Flawless Rechargable Facial Trimmer/IMG-20250822-WA0074.jpg",
        "description": "High-quality Flawless Rechargable Facial Trimmer for your everyday needs."
    },
    {
        "id": 146,
        "category": "General",
        "name": "Foldable Laundry basket - Small",
        "price": "989",
        "originalPrice": "9418",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Foldable Laundry basket - Small/WhatsApp Image 2025-08-21 at 19.06.49_d37ccf18.jpg",
        "description": "High-quality Foldable Laundry basket - Small for your everyday needs."
    },
    {
        "id": 147,
        "category": "General",
        "name": "Food Feeder Baby",
        "price": "2397",
        "originalPrice": "7046",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Food Feeder Baby/WhatsApp Image 2025-08-18 at 15.15.57_906c798f.jpg",
        "description": "High-quality Food Feeder Baby for your everyday needs."
    },
    {
        "id": 148,
        "category": "General",
        "name": "Foot Grind Tool",
        "price": "5173",
        "originalPrice": "8612",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Foot Grind Tool/WhatsApp Image 2025-08-18 at 15.18.11_399a16c9.jpg",
        "description": "High-quality Foot Grind Tool for your everyday needs."
    },
    {
        "id": 149,
        "category": "General",
        "name": "Fridge Cover With Pocket",
        "price": "2516",
        "originalPrice": "8378",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Fridge Cover With Pocket/WhatsApp Image 2025-08-19 at 19.35.14_b86a5c3a.jpg",
        "description": "High-quality Fridge Cover With Pocket for your everyday needs."
    },
    {
        "id": 150,
        "category": "General",
        "name": "Homax Jewelry Box With Mirror",
        "price": "832",
        "originalPrice": "9932",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Homax Jewelry Box With Mirror/WhatsApp Image 2025-08-21 at 19.10.35_057d8207.jpg",
        "description": "High-quality Homax Jewelry Box With Mirror for your everyday needs."
    },
    {
        "id": 151,
        "category": "General",
        "name": "i12 Air Pod",
        "price": "1658",
        "originalPrice": "9640",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/i12 Air Pod/WhatsApp Image 2025-08-19 at 19.34.03_ba1c73cb.jpg",
        "description": "High-quality i12 Air Pod for your everyday needs."
    },
    {
        "id": 152,
        "category": "General",
        "name": "JBL Charge 3 Mini",
        "price": "2708",
        "originalPrice": "6824",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/JBL Charge 3 Mini/WhatsApp Image 2025-08-19 at 19.33.13_5cc5447e.jpg",
        "description": "High-quality JBL Charge 3 Mini for your everyday needs."
    },
    {
        "id": 153,
        "category": "General",
        "name": "Kids Summer Sunglasses",
        "price": "5207",
        "originalPrice": "9751",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Kids Summer Sunglasses/WhatsApp Image 2025-08-19 at 19.43.55_aafc55ca.jpg",
        "description": "High-quality Kids Summer Sunglasses for your everyday needs."
    },
    {
        "id": 154,
        "category": "General",
        "name": "Koleer Portable Bass Speaker",
        "price": "3952",
        "originalPrice": "8227",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Koleer Portable Bass Speaker/WhatsApp Image 2025-08-21 at 19.14.08_77c8bfe9.jpg",
        "description": "High-quality Koleer Portable Bass Speaker for your everyday needs."
    },
    {
        "id": 155,
        "category": "General",
        "name": "Marken 4 Way Extension Cord - 3M",
        "price": "2135",
        "originalPrice": "10145",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Marken 4 Way Extension Cord - 3M/WhatsApp Image 2025-08-19 at 19.32.59_ecdf4bc1.jpg",
        "description": "High-quality Marken 4 Way Extension Cord - 3M for your everyday needs."
    },
    {
        "id": 156,
        "category": "General",
        "name": "Meat Tenderizer",
        "price": "1743",
        "originalPrice": "8946",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Meat Tenderizer/WhatsApp Image 2025-08-21 at 18.54.16_0f5a8b8b.jpg",
        "description": "High-quality Meat Tenderizer for your everyday needs."
    },
    {
        "id": 157,
        "category": "General",
        "name": "Metal Mesh Vegetable Basket",
        "price": "715",
        "originalPrice": "7170",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Metal Mesh Vegetable Basket/WhatsApp Image 2025-08-21 at 19.10.20_2b8d0872.jpg",
        "description": "High-quality Metal Mesh Vegetable Basket for your everyday needs."
    },
    {
        "id": 158,
        "category": "General",
        "name": "Micro Fiber Car Cleaning Cloth",
        "price": "5294",
        "originalPrice": "6710",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Micro Fiber Car Cleaning Cloth/WhatsApp Image 2025-08-20 at 19.59.15_0d3c4924.jpg",
        "description": "High-quality Micro Fiber Car Cleaning Cloth for your everyday needs."
    },
    {
        "id": 159,
        "category": "General",
        "name": "Mini Hair Straightner",
        "price": "977",
        "originalPrice": "8621",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Mini Hair Straightner/IMG-20250821-WA0042.jpg",
        "description": "High-quality Mini Hair Straightner for your everyday needs."
    },
    {
        "id": 160,
        "category": "General",
        "name": "Mini Portable Juicer",
        "price": "3235",
        "originalPrice": "6688",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Mini Portable Juicer/IMG-20250821-WA0108.jpg",
        "description": "High-quality Mini Portable Juicer for your everyday needs."
    },
    {
        "id": 161,
        "category": "General",
        "name": "Nima Electric Grinder",
        "price": "3349",
        "originalPrice": "8644",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Nima Electric Grinder/IMG-20250823-WA0028.jpg",
        "description": "High-quality Nima Electric Grinder for your everyday needs."
    },
    {
        "id": 162,
        "category": "General",
        "name": "Pix-Link WiFi Smart Camera",
        "price": "3977",
        "originalPrice": "7009",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Pix-Link WiFi Smart Camera/WhatsApp Image 2025-08-18 at 14.34.03_8559799c.jpg",
        "description": "High-quality Pix-Link WiFi Smart Camera for your everyday needs."
    },
    {
        "id": 163,
        "category": "General",
        "name": "Pizza Tray - 26cm",
        "price": "3736",
        "originalPrice": "8631",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Pizza Tray - 26cm/WhatsApp Image 2025-08-21 at 18.53.34_4cb772ad.jpg",
        "description": "High-quality Pizza Tray - 26cm for your everyday needs."
    },
    {
        "id": 164,
        "category": "General",
        "name": "Portable Electronic Scale",
        "price": "1354",
        "originalPrice": "10829",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Portable Electronic Scale/IMG-20250821-WA0210.jpg",
        "description": "High-quality Portable Electronic Scale for your everyday needs."
    },
    {
        "id": 165,
        "category": "General",
        "name": "Portable Mini Flashlight Q5+COB Led Headlamp",
        "price": "5005",
        "originalPrice": "10560",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Portable Mini Flashlight Q5+COB Led Headlamp/WhatsApp Image 2025-08-20 at 19.59.04_2847ce35.jpg",
        "description": "High-quality Portable Mini Flashlight Q5+COB Led Headlamp for your everyday needs."
    },
    {
        "id": 166,
        "category": "General",
        "name": "Portable Mini Foot Air Pump With Meter",
        "price": "5008",
        "originalPrice": "8013",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Portable Mini Foot Air Pump With Meter/WhatsApp Image 2025-08-20 at 19.56.14_006a8717.jpg",
        "description": "High-quality Portable Mini Foot Air Pump With Meter for your everyday needs."
    },
    {
        "id": 167,
        "category": "General",
        "name": "RGB Led Ring Light With Stand - MJ26",
        "price": "4172",
        "originalPrice": "10414",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/RGB Led Ring Light With Stand - MJ26/WhatsApp Image 2025-08-20 at 20.21.16_0c66b711.jpg",
        "description": "High-quality RGB Led Ring Light With Stand - MJ26 for your everyday needs."
    },
    {
        "id": 168,
        "category": "General",
        "name": "Self Adhesive Wooden Strip Wall Sticker 45x5m",
        "price": "3457",
        "originalPrice": "10869",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Self Adhesive Wooden Strip Wall Sticker 45x5m/WhatsApp Image 2025-08-21 at 19.15.15_99bf980e.jpg",
        "description": "High-quality Self Adhesive Wooden Strip Wall Sticker 45x5m for your everyday needs."
    },
    {
        "id": 169,
        "category": "General",
        "name": "SF 400 Kitchen Scale",
        "price": "1989",
        "originalPrice": "6615",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/SF 400 Kitchen Scale/IMG-20250821-WA0065.jpg",
        "description": "High-quality SF 400 Kitchen Scale for your everyday needs."
    },
    {
        "id": 170,
        "category": "General",
        "name": "Shower Curtain with Holes",
        "price": "4090",
        "originalPrice": "6163",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Shower Curtain with Holes/WhatsApp Image 2025-08-20 at 19.58.52_d0883b27.jpg",
        "description": "High-quality Shower Curtain with Holes for your everyday needs."
    },
    {
        "id": 171,
        "category": "General",
        "name": "Silica Gel Bath",
        "price": "5437",
        "originalPrice": "7760",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Silica Gel Bath/WhatsApp Image 2025-08-18 at 15.19.03_c7fe9bf0.jpg",
        "description": "High-quality Silica Gel Bath for your everyday needs."
    },
    {
        "id": 172,
        "category": "General",
        "name": "Silicone brush and spatula set",
        "price": "3156",
        "originalPrice": "6183",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Silicone brush and spatula set/WhatsApp Image 2025-08-18 at 15.18.01_ac1124c4.jpg",
        "description": "High-quality Silicone brush and spatula set for your everyday needs."
    },
    {
        "id": 173,
        "category": "General",
        "name": "silicone massage bath brush",
        "price": "1269",
        "originalPrice": "8688",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/silicone massage bath brush/WhatsApp Image 2025-08-20 at 20.15.48_32262a9b.jpg",
        "description": "High-quality silicone massage bath brush for your everyday needs."
    },
    {
        "id": 174,
        "category": "General",
        "name": "Skate Board - Small",
        "price": "1765",
        "originalPrice": "6746",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Skate Board - Small/WhatsApp Image 2025-08-19 at 19.33.50_0b084bfe.jpg",
        "description": "High-quality Skate Board - Small for your everyday needs."
    },
    {
        "id": 175,
        "category": "General",
        "name": "Slim & Lift Vest",
        "price": "3306",
        "originalPrice": "8961",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Slim & Lift Vest/IMG-20250821-WA0023.jpg",
        "description": "High-quality Slim & Lift Vest for your everyday needs."
    },
    {
        "id": 176,
        "category": "General",
        "name": "Soap Pump Dispenser",
        "price": "2613",
        "originalPrice": "8719",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Soap Pump Dispenser/IMG-20250822-WA0076.jpg",
        "description": "High-quality Soap Pump Dispenser for your everyday needs."
    },
    {
        "id": 177,
        "category": "General",
        "name": "Sokani Hand Mixer 133",
        "price": "1180",
        "originalPrice": "7809",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Sokani Hand Mixer 133/WhatsApp Image 2025-08-18 at 21.15.19_717e1a12.jpg",
        "description": "High-quality Sokani Hand Mixer 133 for your everyday needs."
    },
    {
        "id": 178,
        "category": "General",
        "name": "Solar Wall Lamp 100 Led Light",
        "price": "5378",
        "originalPrice": "10637",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Solar Wall Lamp 100 Led Light/IMG-20250821-WA0123.jpg",
        "description": "High-quality Solar Wall Lamp 100 Led Light for your everyday needs."
    },
    {
        "id": 179,
        "category": "General",
        "name": "Steam Cooking Pot",
        "price": "4196",
        "originalPrice": "7339",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Steam Cooking Pot/IMG-20250818-WA0026.jpg",
        "description": "High-quality Steam Cooking Pot for your everyday needs."
    },
    {
        "id": 180,
        "category": "General",
        "name": "Table Mate 2",
        "price": "1552",
        "originalPrice": "10799",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Table Mate 2/WhatsApp Image 2025-08-21 at 18.54.27_ed6c4f22.jpg",
        "description": "High-quality Table Mate 2 for your everyday needs."
    },
    {
        "id": 181,
        "category": "General",
        "name": "Transparent Flower Design Umbrella",
        "price": "2926",
        "originalPrice": "8443",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Transparent Flower Design Umbrella/IMG-20250822-WA0067.jpg",
        "description": "High-quality Transparent Flower Design Umbrella for your everyday needs."
    },
    {
        "id": 182,
        "category": "General",
        "name": "Ultrasonic Dog Chaser",
        "price": "4208",
        "originalPrice": "9398",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Ultrasonic Dog Chaser/WhatsApp Image 2025-08-21 at 19.14.17_56a89fdd.jpg",
        "description": "High-quality Ultrasonic Dog Chaser for your everyday needs."
    },
    {
        "id": 183,
        "category": "General",
        "name": "Umbrella Bike Phone Holder",
        "price": "4259",
        "originalPrice": "10760",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Umbrella Bike Phone Holder/WhatsApp Image 2025-08-19 at 09.50.27_afc35c6f.jpg",
        "description": "High-quality Umbrella Bike Phone Holder for your everyday needs."
    },
    {
        "id": 184,
        "category": "General",
        "name": "Unikmax 4 In 1 65w Fast Charging Cable",
        "price": "5094",
        "originalPrice": "8271",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Unikmax 4 In 1 65w Fast Charging Cable/WhatsApp Image 2025-08-19 at 19.33.42_60689ab6.jpg",
        "description": "High-quality Unikmax 4 In 1 65w Fast Charging Cable for your everyday needs."
    },
    {
        "id": 185,
        "category": "General",
        "name": "USB Juicer",
        "price": "2701",
        "originalPrice": "7428",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/USB Juicer/IMG-20250823-WA0034.jpg",
        "description": "High-quality USB Juicer for your everyday needs."
    },
    {
        "id": 186,
        "category": "General",
        "name": "Valex Quartz Black Round Wall Clock",
        "price": "1437",
        "originalPrice": "7650",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Valex Quartz Black Round Wall Clock/WhatsApp Image 2025-08-19 at 19.32.57_b44f7c90.jpg",
        "description": "High-quality Valex Quartz Black Round Wall Clock for your everyday needs."
    },
    {
        "id": 187,
        "category": "General",
        "name": "Viokai Golden Mens Watch",
        "price": "1561",
        "originalPrice": "7963",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Viokai Golden Mens Watch/WhatsApp Image 2025-08-21 at 19.14.27_85ef9564.jpg",
        "description": "High-quality Viokai Golden Mens Watch for your everyday needs."
    },
    {
        "id": 188,
        "category": "General",
        "name": "Washing Glove",
        "price": "1748",
        "originalPrice": "9661",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Washing Glove/WhatsApp Image 2025-08-20 at 20.03.40_c456844a.jpg",
        "description": "High-quality Washing Glove for your everyday needs."
    },
    {
        "id": 189,
        "category": "General",
        "name": "WaterProof Motor Bike Cover - 100x200",
        "price": "4457",
        "originalPrice": "9681",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/WaterProof Motor Bike Cover - 100x200/WhatsApp Image 2025-08-20 at 20.11.18_f6167938.jpg",
        "description": "High-quality WaterProof Motor Bike Cover - 100x200 for your everyday needs."
    },
    {
        "id": 190,
        "category": "General",
        "name": "Wireless Car Polisher Gun",
        "price": "850",
        "originalPrice": "7522",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Wireless Car Polisher Gun/WhatsApp Image 2025-08-21 at 19.17.00_9f0e81ce.jpg",
        "description": "High-quality Wireless Car Polisher Gun for your everyday needs."
    },
    {
        "id": 191,
        "category": "General",
        "name": "Wood Metal Tissue Holder - B17",
        "price": "2762",
        "originalPrice": "8611",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Wood Metal Tissue Holder - B17/WhatsApp Image 2025-08-21 at 19.12.37_51716690.jpg",
        "description": "High-quality Wood Metal Tissue Holder - B17 for your everyday needs."
    },
    {
        "id": 192,
        "category": "General",
        "name": "X Type MicroFIbre Mop",
        "price": "4223",
        "originalPrice": "9431",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/X Type MicroFIbre Mop/WhatsApp Image 2025-08-20 at 19.59.48_d96cbea3.jpg",
        "description": "High-quality X Type MicroFIbre Mop for your everyday needs."
    },
    {
        "id": 193,
        "category": "General",
        "name": "Xtreme 4 Led Wireless Bluetooth Speaker",
        "price": "4941",
        "originalPrice": "7667",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Xtreme 4 Led Wireless Bluetooth Speaker/WhatsApp Image 2025-08-19 at 19.32.51_5c8ae146.jpg",
        "description": "High-quality Xtreme 4 Led Wireless Bluetooth Speaker for your everyday needs."
    },
    {
        "id": 194,
        "category": "General",
        "name": "Yonsa Electric Cooker - 18cm",
        "price": "3991",
        "originalPrice": "6011",
        "discount": "50%",
        "saveDetail": "Variable",
        "image": "/products/Yonsa Electric Cooker - 18cm/WhatsApp Image 2025-08-18 at 12.09.35_fe79efef.jpg",
        "description": "High-quality Yonsa Electric Cooker - 18cm for your everyday needs."
    }
];
